# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: detect-aws-credentials
    -   id: detect-private-key

# terraform
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 'v1.77.0' # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
    -   id: terraform_tflint
        args:
        - --args=--disable-rule=terraform_required_providers
        - --args=--disable-rule=terraform_required_version
    # -   id: terraform_tfsec
    -   id: infracost_breakdown
        args:
        - --args=--path=.
        verbose: true # Always show
# ---
